receivers:
  jmx:
    jar_path: /otel-collector-jars/opentelemetry-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://kafka:9999/jmxrmi
    target_system: kafka
    collection_interval: 15s

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [jmx]
      processors: [batch]
      exporters: [prometheus]
